version: '3.8'

services:
  web:
    build: .
    volumes:
      - ./data:/app/data
      - ./migrations:/app/migrations
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db/bankruptcy_db
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: bankruptcy_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d bankruptcy_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata: